export const CONTRACT_NAME = 't02_counter';

export const CONTRACT_INDEX = BigInt(2827);
export const RAW_SCHEMA =
  '//8DAQAAAAsAAAB0MDJfY291bnRlcgADAAAACQAAAGRlY3JlbWVudAMVAQAAABEAAABQYXJzZUFjY291bnRFcnJvcgIJAAAAaW5jcmVtZW50AxUBAAAAEQAAAFBhcnNlQWNjb3VudEVycm9yAgQAAAB2aWV3ARQAAQAAAAUAAABjb3VudAkA';
